services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-for-api
    ports:
      - "4567:4566" # LocalStack endpoint
    environment:
      - SERVICES=s3,sts
      - DEBUG=1
    volumes:
      - ./localstack:/etc/localstack/init/ready.d